package proofs.jakartakt

import example.jakartakt.Checkout
import example.jakartakt.Req
import example.jakartakt.ReqConstraints
import org.bmc4j.Bmc
import org.bmc4j.BmcProof
import org.bmc4j.Verdict

/**
 * Proofs over a KOTLIN [Req] DTO whose `ReqConstraints.assumeValid` helper is generated by the
 * `bmc-constraints-jakarta` **KSP** SymbolProcessor — no Java mirror class. The Kotlin path is wired
 * exactly like the Java one ([proofs.jakarta.ValidationProofTests]): JBMC makes the `Req` parameter a
 * symbolic input and `assumeValid` constrains it to the Jakarta-valid domain.
 */
class KotlinValidationProofTests {

    /**
     * ACCEPTANCE: the KSP-generated helper assumes the Jakarta bounds, so `qty >= 1 && cents >= 0`
     * holds for every valid `Req` — the proof VERIFIES.
     */
    @BmcProof
    fun assume_valid_constrains_qty_and_cents(r: Req) {
        ReqConstraints.assumeValid(r)
        Bmc.check(r.qty >= 1 && r.cents >= 0)
    }

    /** PASSES: `unitPriceFloor` never divides by zero because `@Min(1)` puts `qty >= 1` in the domain. */
    @BmcProof
    fun unit_price_floor_is_safe_for_every_valid_req(r: Req) {
        ReqConstraints.assumeValid(r)
        Checkout.unitPriceFloor(r)
    }

    /**
     * FAILS: `ageOrNull` is a boxed `Int?` without `@NotNull`, so `null` is VALID — and `ageBucket`
     * unboxes it. The refutation exists only because the generated assume is null-guarded
     * (`ageOrNull == null || ageOrNull <= 120`), keeping the valid-null objects IN the proof domain.
     */
    // Expected verdict: REFUTED - a valid Req with a null ageOrNull crashes ageBucket().
    @BmcProof(expect = Verdict.REFUTED)
    fun age_bucket_handles_every_valid_req(r: Req) {
        ReqConstraints.assumeValid(r)
        Checkout.ageBucket(r)
    }
}
