package org.bmc4j.engine;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Renders the Java source of a contract <b>stub</b> method for the replace direction
 *. For a contracted method {@code T C.f(P... args)} the generated stub has the
 * same signature and body:
 *
 * <pre>{@code
 * public static T f__stub(P... args) {
 *     org.bmc4j.Bmc.check(C.<requires>(args));     // assert the precondition (caller's duty)
 *     T r = org.cprover.CProver.nondetT();               // an arbitrary result...
 *     org.bmc4j.Bmc.assume(C.<ensures>(r, args));  // ...constrained by the postcondition
 *     return r;
 * }
 * }</pre>
 *
 * {@link ContractRewriter} redirects call sites of {@code C.f} to this stub, so callers
 * reuse the contract instead of re-analyzing the body. The stub is the analysis-time
 * counterpart of the enforce-proof that discharges the same predicates against the real
 * body. v1: static, value-returning methods.
 */
public final class ContractStubGenerator {

    private ContractStubGenerator() {
    }

    /** One contracted method to stub. */
    public static final class Contract {
        /** Production class declaring the contracted method (the enforce-proof calls it; the
         *  replace rewriter redirects its call sites). */
        public final String targetFqn;
        /** Class holding the {@code static boolean} predicate methods — the test-side contract type. */
        public final String predicateOwnerFqn;
        public final String methodName;
        public final String returnType;
        /** Ordered (type, name) parameters of the contracted method. */
        public final List<Map.Entry<String, String>> params;
        /** static boolean predicate over params, or null. */
        public final String requires;
        /** static boolean predicate over (result, params), or null. */
        public final String ensures;
        /** Expected verdict of the generated enforce-proof ("VERIFIED" default; demo contracts
         *  declare "REFUTED"/"VACUOUS" via {@code @BmcContractsFor(expectEnforce = ...)}). */
        public final String expectEnforce;

        public Contract(String targetFqn, String predicateOwnerFqn, String methodName, String returnType,
                        List<Map.Entry<String, String>> params, String requires, String ensures) {
            this(targetFqn, predicateOwnerFqn, methodName, returnType, params, requires, ensures,
                    "VERIFIED");
        }

        public Contract(String targetFqn, String predicateOwnerFqn, String methodName, String returnType,
                        List<Map.Entry<String, String>> params, String requires, String ensures,
                        String expectEnforce) {
            this.targetFqn = targetFqn;
            this.predicateOwnerFqn = predicateOwnerFqn;
            this.methodName = methodName;
            this.returnType = returnType;
            this.params = params;
            this.requires = requires;
            this.ensures = ensures;
            this.expectEnforce = expectEnforce == null ? "VERIFIED" : expectEnforce;
        }
    }

    /** Render a stub class holding a {@code <method>__stub} method per contract. */
    public static String generate(String packageName, String stubClassName, List<Contract> contracts) {
        StringBuilder sb = new StringBuilder();
        if (packageName != null && !packageName.isEmpty()) {
            sb.append("package ").append(packageName).append(";\n\n");
        }
        sb.append("// Generated by bmc-contracts (replace stubs). Do not edit.\n");
        sb.append("public final class ").append(stubClassName).append(" {\n\n");
        sb.append("    private ").append(stubClassName).append("() {}\n");
        for (Contract c : contracts) {
            sb.append('\n').append(method(c));
        }
        sb.append("}\n");
        return sb.toString();
    }

    private static String method(Contract c) {
        String paramList = c.params.stream()
                .map(p -> p.getKey() + " " + p.getValue())
                .collect(Collectors.joining(", "));
        String argList = c.params.stream().map(Map.Entry::getValue).collect(Collectors.joining(", "));

        StringBuilder b = new StringBuilder();
        b.append("    public static ").append(c.returnType).append(' ')
                .append(c.methodName).append("__stub(").append(paramList).append(") {\n");
        if (c.requires != null) {
            b.append("        org.bmc4j.Bmc.check(")
                    .append(c.predicateOwnerFqn).append('.').append(c.requires)
                    .append('(').append(argList).append("));\n");
        }
        if ("void".equals(c.returnType)) {
            // Degenerate: no result to constrain (v1 targets value-returning methods).
            b.append("    }\n");
            return b.toString();
        }
        b.append("        ").append(c.returnType).append(" r = ").append(nondetExpr(c.returnType)).append(";\n");
        if (c.ensures != null) {
            String ensuresArgs = argList.isEmpty() ? "r" : "r, " + argList;
            b.append("        org.bmc4j.Bmc.assume(")
                    .append(c.predicateOwnerFqn).append('.').append(c.ensures)
                    .append('(').append(ensuresArgs).append("));\n");
        }
        b.append("        return r;\n");
        b.append("    }\n");
        return b.toString();
    }

    /** The CProver nondet call producing an arbitrary value of {@code type}. Package-private:
     *  shared with {@link ContractEnforceProofGenerator}, which builds nondet enforce-proof args. */
    static String nondetExpr(String type) {
        switch (type) {
            case "int":     return "org.cprover.CProver.nondetInt()";
            case "long":    return "org.cprover.CProver.nondetLong()";
            case "short":   return "org.cprover.CProver.nondetShort()";
            case "byte":    return "org.cprover.CProver.nondetByte()";
            case "char":    return "org.cprover.CProver.nondetChar()";
            case "boolean": return "org.cprover.CProver.nondetBoolean()";
            case "float":   return "org.cprover.CProver.nondetFloat()";
            case "double":  return "org.cprover.CProver.nondetDouble()";
            default:        return "(" + type + ") org.cprover.CProver.nondetWithoutNull()";
        }
    }
}
