package org.bmc4j.engine;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

/**
 * Renders the Java source of a contract <b>enforce-proof</b> class. For a
 * contracted method {@code T C.f(P... args)} it generates a {@code @BmcProof} that
 * discharges the contract against the <em>real</em> body:
 *
 * <pre>{@code
 * @org.bmc4j.BmcProof
 * public void enforce__f() {
 *     P0 a0 = nondet(); P1 a1 = nondet(); ...
 *     org.bmc4j.Bmc.assume(C.<requires>(a0, a1));   // grant the precondition
 *     T result = C.f(a0, a1);                             // the REAL method
 *     org.bmc4j.Bmc.check(C.<ensures>(result, a0, a1)); // it must establish the postcondition
 * }
 * }</pre>
 *
 * This is the counterpart of {@link ContractStubGenerator}'s replace-stub: the stub
 * <em>assumes</em> the contract for callers; this proof <em>guarantees</em> it once, so a
 * false contract turns the build red. "Annotate ≠ proven" is therefore structural —
 * annotating a method emits a proof obligation that must pass.
 *
 * <p>Run modularly: {@link JbmcBackend} excludes this proof class as a caller when rewriting
 * (see {@link ContractRewriter}), so the proof's direct call to {@code C.f} hits the real
 * body while {@code C.f}'s own contracted callees — including a recursive self-call — are
 * summarized. The enforce of a recursive method is thus the inductive step, not a full unroll.
 */
public final class ContractEnforceProofGenerator {

    private ContractEnforceProofGenerator() {
    }

    /** Render an enforce-proof class holding an {@code enforce__<method>} per contract. */
    public static String generate(String packageName, String className,
                                  List<ContractStubGenerator.Contract> contracts) {
        StringBuilder sb = new StringBuilder();
        if (packageName != null && !packageName.isEmpty()) {
            sb.append("package ").append(packageName).append(";\n\n");
        }
        sb.append("// Generated by bmc-contracts (enforce proofs). Do not edit.\n");
        // Not final and with a default constructor: JUnit instantiates the proof class.
        sb.append("public class ").append(className).append(" {\n");
        for (ContractStubGenerator.Contract c : contracts) {
            sb.append('\n').append(proof(c));
        }
        sb.append("}\n");
        return sb.toString();
    }

    private static String proof(ContractStubGenerator.Contract c) {
        // a0, a1, ... so generated names never collide with the user's parameter names.
        List<String> args = IntStream.range(0, c.params.size())
                .mapToObj(i -> "a" + i).collect(Collectors.toList());
        String argList = String.join(", ", args);

        StringBuilder b = new StringBuilder();
        if ("VERIFIED".equals(c.expectEnforce)) {
            b.append("    @org.bmc4j.BmcProof\n");
        } else {
            // A demo contract declared its expected enforce verdict (deliberately false /
            // vacuous-precondition demos) — propagate it so the generated proof self-asserts.
            b.append("    // Expected verdict: ").append(c.expectEnforce)
                    .append(" - declared via @BmcContractsFor(expectEnforce = ...).\n");
            b.append("    @org.bmc4j.BmcProof(expect = org.bmc4j.Verdict.")
                    .append(c.expectEnforce).append(")\n");
        }
        b.append("    public void enforce__").append(c.methodName).append("() {\n");
        for (int i = 0; i < c.params.size(); i++) {
            String type = c.params.get(i).getKey();
            b.append("        ").append(type).append(' ').append(args.get(i))
                    .append(" = ").append(ContractStubGenerator.nondetExpr(type)).append(";\n");
        }
        if (c.requires != null) {
            b.append("        org.bmc4j.Bmc.assume(")
                    .append(c.predicateOwnerFqn).append('.').append(c.requires)
                    .append('(').append(argList).append("));\n");
        }
        String call = c.targetFqn + '.' + c.methodName + '(' + argList + ')';
        if ("void".equals(c.returnType)) {
            // Degenerate (v1 targets value-returning methods): exercise the body only.
            b.append("        ").append(call).append(";\n");
            b.append("    }\n");
            return b.toString();
        }
        b.append("        ").append(c.returnType).append(" result = ").append(call).append(";\n");
        if (c.ensures != null) {
            String ensuresArgs = argList.isEmpty() ? "result" : "result, " + argList;
            b.append("        org.bmc4j.Bmc.check(")
                    .append(c.predicateOwnerFqn).append('.').append(c.ensures)
                    .append('(').append(ensuresArgs).append("));\n");
        }
        b.append("    }\n");
        return b.toString();
    }
}
