package org.bmc4j.engine;

import java.io.IOException;
import java.lang.reflect.Method;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Writes a refuted proof's counterexample to a runnable {@code @Test} scratch file (v2):
 * {@code build/bmc4j/replays/<Class>_<method>Replay.java}. The file reconstructs the concrete inputs
 * from the counterexample and leaves a clearly-marked spot to invoke the code under test, so the
 * developer can drop it into a test source set and step through it in a debugger.
 *
 * <p>It is a <b>scratch artifact</b>: never auto-added to any source set (the user opts into running
 * it). The renderer reuses {@link ReplayRenderer}'s literal rendering, so the inputs are always
 * compilable; the invocation is left as a {@code // TODO} comment because the symbolic proof body can
 * make several calls and bmc4j cannot soundly pick the one true target call to fabricate.
 *
 * <p>Writing is best-effort: any I/O failure returns {@code null} (no file, no block reference) so a
 * read-only or sandboxed filesystem never turns a refutation into a crash.
 */
public final class ReplayTestWriter {

    private ReplayTestWriter() {
    }

    /** Output dir, overridable for tests via {@code -Dbmc.replayDir}. */
    static Path outputDir() {
        String override = System.getProperty("bmc.replayDir");
        if (override != null && !override.isBlank()) {
            return Path.of(override.trim());
        }
        return Path.of("build", "bmc4j", "replays");
    }

    /**
     * Write the replay test for {@code violation} and return its path (as a string), or {@code null}
     * if there is nothing to render or the write failed.
     */
    public static String write(String entryFunctionFqn, Method proofMethod,
                               JbmcResult.Violation violation) {
        String body = ReplayRenderer.render(entryFunctionFqn, proofMethod, violation);
        if (body == null) {
            return null;
        }
        String simpleClass = simpleClassOf(entryFunctionFqn);
        String methodName = methodOf(entryFunctionFqn);
        String testClass = sanitize(simpleClass) + "_" + sanitize(methodName) + "Replay";
        String source = renderSource(testClass, entryFunctionFqn, proofMethod, violation);
        try {
            Path dir = outputDir();
            Files.createDirectories(dir);
            Path file = dir.resolve(testClass + ".java");
            Files.writeString(file, source, StandardCharsets.UTF_8);
            return file.toString();
        } catch (IOException | RuntimeException e) {
            return null; // best-effort: never let a write failure mask the refutation
        }
    }

    /** The full Java source of the scratch replay test. */
    static String renderSource(String testClass, String entryFunctionFqn, Method proofMethod,
                               JbmcResult.Violation violation) {
        StringBuilder sb = new StringBuilder();
        sb.append("// Auto-generated by bmc4j — a SCRATCH replay of a refuted proof.\n");
        sb.append("// Not on any source set. Drop it into src/test/java, wire the invocation marked\n");
        sb.append("// TODO below, and run it under a debugger to reproduce the counterexample.\n");
        sb.append("import org.junit.jupiter.api.Test;\n\n");
        sb.append("class ").append(testClass).append(" {\n\n");
        sb.append("    @Test\n");
        sb.append("    void replay() {\n");
        // Emit the declarations directly from the renderer's block (strip its "replay:" framing).
        for (String l : declarationLines(entryFunctionFqn, proofMethod, violation)) {
            sb.append("        ").append(l).append('\n');
        }
        sb.append("        // TODO: invoke the same code path the proof exercised, e.g.\n");
        sb.append("        //   ").append(simpleClassOf(entryFunctionFqn)).append('.')
                .append(methodOf(entryFunctionFqn)).append("(...);\n");
        sb.append("    }\n");
        sb.append("}\n");
        return sb.toString();
    }

    /** The bare declaration lines (no {@code replay:} header / hint comment) for the test body. */
    private static java.util.List<String> declarationLines(String entryFunctionFqn, Method proofMethod,
                                                           JbmcResult.Violation violation) {
        java.util.List<String> out = new java.util.ArrayList<>();
        String block = ReplayRenderer.render(entryFunctionFqn, proofMethod, violation);
        if (block == null) {
            return out;
        }
        for (String raw : block.split("\n")) {
            String t = raw.trim();
            if (t.isEmpty() || t.equals("replay:") || t.startsWith("// then run")) {
                continue;
            }
            out.add(t);
        }
        return out;
    }

    private static String simpleClassOf(String fqn) {
        String s = stripSig(fqn);
        int dot = s.lastIndexOf('.');
        if (dot <= 0) {
            return s;
        }
        int prev = s.lastIndexOf('.', dot - 1);
        return s.substring(prev + 1, dot);
    }

    private static String methodOf(String fqn) {
        String s = stripSig(fqn);
        int dot = s.lastIndexOf('.');
        return dot >= 0 ? s.substring(dot + 1) : s;
    }

    private static String stripSig(String fqn) {
        int sig = fqn.indexOf(":(");
        return sig >= 0 ? fqn.substring(0, sig) : fqn;
    }

    private static String sanitize(String s) {
        StringBuilder sb = new StringBuilder(s.length());
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            sb.append(Character.isJavaIdentifierPart(c) ? c : '_');
        }
        return sb.length() == 0 ? "X" : sb.toString();
    }
}
