package org.bmc4j.engine

import com.google.gson.JsonParser
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import org.objectweb.asm.ClassReader
import org.objectweb.asm.ClassVisitor
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes
import java.nio.file.Files
import java.nio.file.Path
import java.util.concurrent.atomic.AtomicBoolean

/**
 * Unit tests for the stub-detection positive floor. The floor exists because the stub harvest keys
 * on a literal engine string — a format drift in a `-Dbmc.jbmc` engine silently empties it.
 * These tests pin the pieces that make the canary a valid floor (its stub survives the filter, its
 * bytecode really calls the missing method, the harvest extracts it from the pinned message shape)
 * and the failure path's behavior (loud engine-infrastructure UNKNOWN, memoized, marker-trusting).
 * The success path runs live in every example module: the first all-modeled green triggers the
 * canary against the bundled engine.
 */
internal class StubHarvestFloorTest {

    @Test
    fun canary_stub_survives_the_signal_filter() {
        // The floor exercises the FULL harvest pipeline, filter included — if a future StubFilter
        // rule swallowed the canary's package, every floor probe would fail (loud, but wrong).
        assertTrue(StubFilter.isSignal(StubHarvestFloor.CANARY_STUB_FQN),
                "the canary stub must be classified as signal or the floor cannot work")
    }

    @Test
    fun canary_harvests_from_the_pinned_message_shape() {
        // Ties the canary constant to the parser's opaque-symbol extraction: the exact message the
        // engine emits for the canary's missing method must harvest to CANARY_STUB_FQN.
        val json = """
            [
              {"messageType":"STATUS-MESSAGE",
               "messageText":"Generating codet:  new opaque symbol: method 'java::bmc.canary.Missing.gone:()V'"}
            ]""".trimIndent()
        val stubs = JbmcOutputParser.harvestStubs(
                JsonParser.parseString(json).asJsonArray)
        assertEquals(listOf(StubHarvestFloor.CANARY_STUB_FQN), stubs,
                "the canary's opaque-symbol message must harvest to the canary FQN")
    }

    @Test
    fun probe_class_really_calls_the_missing_method() {
        // Guards the generated bytecode against bitrot: the probe must INVOKESTATIC the missing
        // class that CANARY_STUB_FQN names, or the engine has nothing to stub.
        val sawCall = AtomicBoolean()
        ClassReader(StubHarvestFloor.probeClass()).accept(object : ClassVisitor(Opcodes.ASM9) {
            override fun visitMethod(a: Int, name: String?, d: String?, s: String?,
                                     ex: Array<String>?): MethodVisitor {
                return object : MethodVisitor(Opcodes.ASM9) {
                    override fun visitMethodInsn(op: Int, owner: String?, m: String?,
                                                 desc: String?, i: Boolean) {
                        if (op == Opcodes.INVOKESTATIC && owner == "bmc/canary/Missing"
                                && m == "gone") {
                            sawCall.set(true)
                        }
                    }
                }
            }
        }, 0)
        assertTrue(sawCall.get(), "the probe must call bmc.canary.Missing.gone")
        assertTrue(StubHarvestFloor.CANARY_STUB_FQN == "bmc.canary.Missing.gone",
                "constant and bytecode must name the same missing method")
    }

    @Test
    fun unverifiable_engine_fails_loud_and_memoizes(@TempDir home: Path) {
        runWithHome(home) {
            val identity = "test-engine-bogus-" + System.nanoTime()
            val before = StubHarvestFloor.CANARY_RUNS.get()

            // A jbmc path that cannot run: the canary cannot vouch -> loud infrastructure UNKNOWN.
            val e = assertThrows(BmcUndecidedError::class.java) {
                StubHarvestFloor.ensure(home.resolve("no-such-jbmc.exe").toString(), identity)
            }
            assertTrue(e.isEngineInfrastructure(),
                    "a failed floor is an engine-infrastructure UNKNOWN (never satisfies expect=UNKNOWN)")
            assertTrue(e.message!!.contains("stub detection"), e.message)
            assertEquals(before + 1, StubHarvestFloor.CANARY_RUNS.get(), "the canary ran once")

            // Same engine identity again: memoized verdict, no second canary run, still loud.
            assertThrows(BmcUndecidedError::class.java) {
                StubHarvestFloor.ensure(home.resolve("no-such-jbmc.exe").toString(), identity)
            }
            assertEquals(before + 1, StubHarvestFloor.CANARY_RUNS.get(),
                    "the floor verdict is memoized per engine identity")
        }
    }

    @Test
    fun disk_marker_from_a_prior_jvm_is_trusted(@TempDir home: Path) {
        runWithHome(home) {
            val identity = "test-engine-marked-" + System.nanoTime()
            val key = identity + '|' + Bmc4jVersion.IDENTITY
            val marker = StubHarvestFloor.markerPath(key)
            Files.createDirectories(marker.parent)
            Files.writeString(marker, "ok\n")

            val before = StubHarvestFloor.CANARY_RUNS.get()
            // Bogus engine path, but the marker says a prior JVM proved this (engine, runtime)
            // pair — the floor passes without running the canary.
            StubHarvestFloor.ensure(home.resolve("no-such-jbmc.exe").toString(), identity)
            assertEquals(before, StubHarvestFloor.CANARY_RUNS.get(),
                    "a disk marker for this engine+runtime skips the canary entirely")
        }
    }

    companion object {
        /** Run `body` with `user.home` redirected so floor markers stay in the temp dir. */
        private fun runWithHome(home: Path, body: () -> Unit) {
            val prev = System.getProperty("user.home")
            System.setProperty("user.home", home.toAbsolutePath().toString())
            try {
                body()
            } finally {
                System.setProperty("user.home", prev)
            }
        }
    }
}
