package org.bmc4j.constraints;

import java.util.List;

/**
 * Renders a reflection-free {@code <Type>Constraints} helper from a model class's
 * extracted constraints. The generated {@code assumeValid} calls
 * {@code org.bmc4j.Bmc.assume(...)} for each constraint, so JBMC sees the
 * preconditions as plain bytecode.
 */
public final class ConstraintCodeGenerator {

    private ConstraintCodeGenerator() {
    }

    /** A model field plus the accessor used to read it and its constraints. */
    public static final class Field {
        public final String accessor;
        public final List<Constraint> constraints;

        public Field(String accessor, List<Constraint> constraints) {
            this.accessor = accessor;
            this.constraints = constraints;
        }
    }

    /**
     * @param packageName        package of the generated class (may be empty)
     * @param generatedSimpleName e.g. {@code UserConstraints}
     * @param targetTypeFqn      the model type, e.g. {@code com.acme.User}
     * @param paramName          the parameter name used in the generated method (e.g. {@code obj})
     * @param fields             fields whose accessors are already expressed in terms of {@code paramName}
     */
    public static String generate(String packageName, String generatedSimpleName,
                                  String targetTypeFqn, String paramName, List<Field> fields) {
        StringBuilder sb = new StringBuilder();
        if (packageName != null && !packageName.isEmpty()) {
            sb.append("package ").append(packageName).append(";\n\n");
        }
        sb.append("// Generated by bmc-constraints from validation annotations. Do not edit.\n");
        sb.append("public final class ").append(generatedSimpleName).append(" {\n\n");
        sb.append("    private ").append(generatedSimpleName).append("() {}\n\n");

        sb.append("    /** Assume ").append(paramName)
                .append(" satisfies its validation constraints. */\n");
        sb.append("    public static void assumeValid(").append(targetTypeFqn).append(' ')
                .append(paramName).append(") {\n");
        // A validated object exists; assume non-null before reading its fields.
        sb.append("        org.bmc4j.Bmc.assume(").append(paramName).append(" != null);\n");
        for (Field f : fields) {
            for (Constraint c : f.constraints) {
                sb.append("        org.bmc4j.Bmc.assume(")
                        .append(c.toExpression(f.accessor)).append(");\n");
            }
        }
        sb.append("    }\n");
        sb.append("}\n");
        return sb.toString();
    }
}
