package org.bmc4j.engine

/**
 * Renders the Java source of a contract **stub** method for the replace direction.
 * For a contracted method `T C.f(P... args)` the generated stub has the
 * same signature and body:
 *
 * ```
 * public static T f__stub(P... args) {
 *     org.bmc4j.Bmc.check(C.<requires>(args));     // assert the precondition (caller's duty)
 *     T r = org.cprover.CProver.nondetT();               // an arbitrary result...
 *     org.bmc4j.Bmc.assume(C.<ensures>(r, args));  // ...constrained by the postcondition
 *     return r;
 * }
 * ```
 *
 * [ContractRewriter] redirects call sites of `C.f` to this stub, so callers
 * reuse the contract instead of re-analyzing the body. The stub is the analysis-time
 * counterpart of the enforce-proof that discharges the same predicates against the real
 * body. v1: static, value-returning methods.
 */
object ContractStubGenerator {

    /** One contracted method to stub. */
    class Contract @JvmOverloads constructor(
            /** Production class declaring the contracted method (the enforce-proof calls it; the
             *  replace rewriter redirects its call sites). */
            @JvmField val targetFqn: String,
            /** Class holding the `static boolean` predicate methods — the test-side contract type. */
            @JvmField val predicateOwnerFqn: String,
            @JvmField val methodName: String,
            @JvmField val returnType: String,
            /** Ordered (type, name) parameters of the contracted method. */
            @JvmField val params: List<Map.Entry<String, String>>,
            /** static boolean predicate over params, or null. */
            @JvmField val requires: String?,
            /** static boolean predicate over (result, params), or null. */
            @JvmField val ensures: String?,
            /** Expected verdict of the generated enforce-proof ("VERIFIED" default; demo contracts
             *  declare "REFUTED"/"VACUOUS" via `@BmcContractsFor(expectEnforce = ...)`). */
            expectEnforce: String? = "VERIFIED") {

        @JvmField
        val expectEnforce: String = expectEnforce ?: "VERIFIED"
    }

    /** Render a stub class holding a `<method>__stub` method per contract. */
    @JvmStatic
    fun generate(packageName: String?, stubClassName: String, contracts: List<Contract>): String =
            buildString {
                if (!packageName.isNullOrEmpty()) {
                    append("package ").append(packageName).append(";\n\n")
                }
                append("// Generated by bmc-contracts (replace stubs). Do not edit.\n")
                append("public final class ").append(stubClassName).append(" {\n\n")
                append("    private ").append(stubClassName).append("() {}\n")
                for (c in contracts) {
                    append('\n').append(method(c))
                }
                append("}\n")
            }

    private fun method(c: Contract): String = buildString {
        val paramList = c.params.joinToString(", ") { "${it.key} ${it.value}" }
        val argList = c.params.joinToString(", ") { it.value }

        append("    public static ").append(c.returnType).append(' ')
                .append(c.methodName).append("__stub(").append(paramList).append(") {\n")
        if (c.requires != null) {
            append("        org.bmc4j.Bmc.check(")
                    .append(c.predicateOwnerFqn).append('.').append(c.requires)
                    .append('(').append(argList).append("));\n")
        }
        if (c.returnType == "void") {
            // Degenerate: no result to constrain (v1 targets value-returning methods).
            append("    }\n")
            return@buildString
        }
        append("        ").append(c.returnType).append(" r = ")
                .append(nondetExpr(c.returnType)).append(";\n")
        if (c.ensures != null) {
            val ensuresArgs = if (argList.isEmpty()) "r" else "r, $argList"
            append("        org.bmc4j.Bmc.assume(")
                    .append(c.predicateOwnerFqn).append('.').append(c.ensures)
                    .append('(').append(ensuresArgs).append("));\n")
        }
        append("        return r;\n")
        append("    }\n")
    }

    /** The CProver nondet call producing an arbitrary value of [type]. Shared with
     *  [ContractEnforceProofGenerator], which builds nondet enforce-proof args. */
    @JvmStatic
    @JvmName("nondetExpr") // internal functions are name-mangled in bytecode; Java callers/tests
    internal fun nondetExpr(type: String): String = when (type) {
        "int" -> "org.cprover.CProver.nondetInt()"
        "long" -> "org.cprover.CProver.nondetLong()"
        "short" -> "org.cprover.CProver.nondetShort()"
        "byte" -> "org.cprover.CProver.nondetByte()"
        "char" -> "org.cprover.CProver.nondetChar()"
        "boolean" -> "org.cprover.CProver.nondetBoolean()"
        "float" -> "org.cprover.CProver.nondetFloat()"
        "double" -> "org.cprover.CProver.nondetDouble()"
        else -> "($type) org.cprover.CProver.nondetWithoutNull()"
    }
}
