package org.bmc4j.engine

/**
 * Renders the Java source of a contract **stub** method for the replace direction.
 * For a contracted static method `T C.f(P... args)` the generated stub has the
 * same signature and body:
 *
 * ```
 * public static T f__stub(P... args) {
 *     org.bmc4j.Bmc.check(C.<requires>(args));     // assert the precondition (caller's duty)
 *     T r = org.cprover.CProver.nondetT();               // an arbitrary result...
 *     org.bmc4j.Bmc.assume(C.<ensures>(r, args));  // ...constrained by the postcondition
 *     return r;
 * }
 * ```
 *
 * For a **pure instance** method `T R.f(P... args)` the stub threads the receiver as an
 * ordinary leading parameter (`self`), exactly where the call site already has it on the
 * operand stack — the predicates take `self` as their first argument after `result`/before
 * `args`:
 *
 * ```
 * public static T f__stub(R self, P... args) {
 *     org.bmc4j.Bmc.check(C.<requires>(self, args));
 *     T r = org.cprover.CProver.nondetT();
 *     org.bmc4j.Bmc.assume(C.<ensures>(r, self, args));
 *     return r;
 * }
 * ```
 *
 * [ContractRewriter] redirects call sites of `C.f` to this stub, so callers
 * reuse the contract instead of re-analyzing the body. The stub is the analysis-time
 * counterpart of the enforce-proof that discharges the same predicates against the real
 * body. Targets: static and **pure instance**, value-returning methods.
 */
object ContractStubGenerator {

    /** One contracted method to stub. */
    class Contract @JvmOverloads constructor(
            /** Production class declaring the contracted method (the enforce-proof calls it; the
             *  replace rewriter redirects its call sites). */
            @JvmField val targetFqn: String,
            /** Class holding the `static boolean` predicate methods — the test-side contract type. */
            @JvmField val predicateOwnerFqn: String,
            @JvmField val methodName: String,
            @JvmField val returnType: String,
            /** Ordered (type, name) parameters of the contracted method. */
            @JvmField val params: List<Map.Entry<String, String>>,
            /** static boolean predicate over params, or null. */
            @JvmField val requires: String?,
            /** static boolean predicate over (result, params), or null. */
            @JvmField val ensures: String?,
            /** Expected verdict of the generated enforce-proof ("VERIFIED" default; demo contracts
             *  declare "REFUTED"/"VACUOUS" via `@BmcContractsFor(expectEnforce = ...)`). */
            expectEnforce: String? = "VERIFIED",
            /** Receiver type (the target class FQN) for a **pure instance** contract, threaded as the
             *  leading `self` parameter of the stub/enforce and predicates; `null` for a static target.
             *  Exact-class binding, like the static case — no virtual dispatch of the target method. */
            @JvmField val receiverType: String? = null) {

        @JvmField
        val expectEnforce: String = expectEnforce ?: "VERIFIED"

        /** True for a pure-instance contract (receiver threaded as `self`). */
        @JvmField
        val isInstance: Boolean = receiverType != null

        /** The receiver parameter name used in generated stubs/proofs; "self" by convention. */
        val receiverName: String
            get() = "self"
    }

    /** Render a stub class holding a `<method>__stub` method per contract. */
    @JvmStatic
    fun generate(packageName: String?, stubClassName: String, contracts: List<Contract>): String =
            buildString {
                if (!packageName.isNullOrEmpty()) {
                    append("package ").append(packageName).append(";\n\n")
                }
                append("// Generated by bmc-contracts (replace stubs). Do not edit.\n")
                append("public final class ").append(stubClassName).append(" {\n\n")
                append("    private ").append(stubClassName).append("() {}\n")
                for (c in contracts) {
                    append('\n').append(method(c))
                }
                append("}\n")
            }

    private fun method(c: Contract): String = buildString {
        // The user's parameters, plus the receiver threaded as a leading `self` for an instance
        // contract. The predicate argument list mirrors the declared predicate shape:
        //   requires(self?, args...)        ensures(result, self?, args...)
        val userParamDecls = c.params.map { "${it.key} ${it.value}" }
        val userArgs = c.params.map { it.value }
        val paramDecls = if (c.isInstance) {
            listOf("${c.receiverType} ${c.receiverName}") + userParamDecls
        } else {
            userParamDecls
        }
        // The arguments passed to the requires predicate: (self?, args...).
        val preArgs = if (c.isInstance) listOf(c.receiverName) + userArgs else userArgs

        append("    public static ").append(c.returnType).append(' ')
                .append(c.methodName).append("__stub(").append(paramDecls.joinToString(", ")).append(") {\n")
        if (c.requires != null) {
            append("        org.bmc4j.Bmc.check(")
                    .append(c.predicateOwnerFqn).append('.').append(c.requires)
                    .append('(').append(preArgs.joinToString(", ")).append("));\n")
        }
        if (c.returnType == "void") {
            // Degenerate: no result to constrain (targets value-returning methods).
            append("    }\n")
            return@buildString
        }
        append("        ").append(c.returnType).append(" r = ")
                .append(nondetExpr(c.returnType)).append(";\n")
        if (c.ensures != null) {
            // ensures(result, self?, args...).
            val postArgs = listOf("r") + preArgs
            append("        org.bmc4j.Bmc.assume(")
                    .append(c.predicateOwnerFqn).append('.').append(c.ensures)
                    .append('(').append(postArgs.joinToString(", ")).append("));\n")
        }
        append("        return r;\n")
        append("    }\n")
    }

    /** The CProver nondet call producing an arbitrary value of [type]. Shared with
     *  [ContractEnforceProofGenerator], which builds nondet enforce-proof args. */
    internal fun nondetExpr(type: String): String = when (type) {
        "int" -> "org.cprover.CProver.nondetInt()"
        "long" -> "org.cprover.CProver.nondetLong()"
        "short" -> "org.cprover.CProver.nondetShort()"
        "byte" -> "org.cprover.CProver.nondetByte()"
        "char" -> "org.cprover.CProver.nondetChar()"
        "boolean" -> "org.cprover.CProver.nondetBoolean()"
        "float" -> "org.cprover.CProver.nondetFloat()"
        "double" -> "org.cprover.CProver.nondetDouble()"
        else -> "($type) org.cprover.CProver.nondetWithoutNull()"
    }
}
