package org.bmc4j.engine

/**
 * Renders the Java source of a contract **enforce-proof** class. For a
 * contracted method `T C.f(P... args)` it generates a `@BmcProof` that
 * discharges the contract against the *real* body:
 *
 * ```
 * @org.bmc4j.BmcProof
 * public void enforce__f() {
 *     P0 a0 = nondet(); P1 a1 = nondet(); ...
 *     org.bmc4j.Bmc.assume(C.<requires>(a0, a1));   // grant the precondition
 *     T result = C.f(a0, a1);                             // the REAL method
 *     org.bmc4j.Bmc.check(C.<ensures>(result, a0, a1)); // it must establish the postcondition
 * }
 * ```
 *
 * This is the counterpart of [ContractStubGenerator]'s replace-stub: the stub
 * *assumes* the contract for callers; this proof *guarantees* it once, so a
 * false contract turns the build red. "Annotate ≠ proven" is therefore structural —
 * annotating a method emits a proof obligation that must pass.
 *
 * Run modularly: `JbmcBackend` excludes this proof class as a caller when rewriting
 * (see [ContractRewriter]), so the proof's direct call to `C.f` hits the real
 * body while `C.f`'s own contracted callees — including a recursive self-call — are
 * summarized. The enforce of a recursive method is thus the inductive step, not a full unroll.
 */
object ContractEnforceProofGenerator {

    /** Render an enforce-proof class holding an `enforce__<method>` per contract. */
    @JvmStatic
    fun generate(packageName: String?, className: String,
                 contracts: List<ContractStubGenerator.Contract>): String = buildString {
        if (!packageName.isNullOrEmpty()) {
            append("package ").append(packageName).append(";\n\n")
        }
        append("// Generated by bmc-contracts (enforce proofs). Do not edit.\n")
        // Not final and with a default constructor: JUnit instantiates the proof class.
        append("public class ").append(className).append(" {\n")
        for (c in contracts) {
            append('\n').append(proof(c))
        }
        append("}\n")
    }

    private fun proof(c: ContractStubGenerator.Contract): String = buildString {
        // a0, a1, ... so generated names never collide with the user's parameter names; the receiver
        // (instance contracts) is a nondet `self` of the target type, threaded into the predicates and
        // used as the call receiver — JBMC treats the entry function's parameters, `this` included, as
        // nondet, so a nondet `self` symbolizes "all receiver states" exactly like a static input.
        val args = List(c.params.size) { "a$it" }
        val argList = args.joinToString(", ")
        // The predicate argument list: requires(self?, args...), ensures(result, self?, args...).
        val preArgs = if (c.isInstance) listOf(SELF) + args else args
        val preArgList = preArgs.joinToString(", ")

        if (c.expectEnforce == "VERIFIED") {
            append("    @org.bmc4j.BmcProof\n")
        } else {
            // A demo contract declared its expected enforce verdict (deliberately false /
            // vacuous-precondition demos) — propagate it so the generated proof self-asserts.
            append("    // Expected verdict: ").append(c.expectEnforce)
                    .append(" - declared via @BmcContractsFor(expectEnforce = ...).\n")
            append("    @org.bmc4j.BmcProof(expect = org.bmc4j.Verdict.")
                    .append(c.expectEnforce).append(")\n")
        }
        append("    public void enforce__").append(c.methodName).append("() {\n")
        if (c.isInstance) {
            // Symbolic receiver: a nondet (non-null) instance of the target type.
            append("        ").append(c.receiverType).append(' ').append(SELF)
                    .append(" = ").append(ContractStubGenerator.nondetExpr(c.receiverType!!)).append(";\n")
        }
        for (i in c.params.indices) {
            val type = c.params[i].key
            append("        ").append(type).append(' ').append(args[i])
                    .append(" = ").append(ContractStubGenerator.nondetExpr(type)).append(";\n")
        }
        if (c.requires != null) {
            append("        org.bmc4j.Bmc.assume(")
                    .append(c.predicateOwnerFqn).append('.').append(c.requires)
                    .append('(').append(preArgList).append("));\n")
        }
        // Static target: Owner.method(args). Instance target: self.method(args) — the REAL body.
        val call = if (c.isInstance) "$SELF.${c.methodName}($argList)"
        else "${c.targetFqn}.${c.methodName}($argList)"
        if (c.returnType == "void") {
            // Degenerate (targets value-returning methods): exercise the body only.
            append("        ").append(call).append(";\n")
            append("    }\n")
            return@buildString
        }
        append("        ").append(c.returnType).append(" result = ").append(call).append(";\n")
        if (c.ensures != null) {
            val ensuresArgs = "result" + if (preArgList.isEmpty()) "" else ", $preArgList"
            append("        org.bmc4j.Bmc.check(")
                    .append(c.predicateOwnerFqn).append('.').append(c.ensures)
                    .append('(').append(ensuresArgs).append("));\n")
        }
        append("    }\n")
    }

    /** The generated receiver-variable name for an instance contract's enforce-proof. */
    private const val SELF = "self"
}
