package org.bmc4j.engine

import java.util.LinkedHashMap

/**
 * The single source of truth for the six environment-INDEPENDENT desugar passes and how they FUSE
 * into one classpath walk.
 *
 * Historically each pass ([CoroutineBytecode], [StringBytecode], [LambdaBytecode], [SwitchBytecode],
 * [ResidualIndyBytecode], [MathBytecode]) ran as its own [ClasspathMirror.mirror] call: every jar/dir
 * was read -> inflated -> ASM-transformed -> deflated -> written, ONCE PER PASS. Over a real consumer
 * classpath (bmc4j + Spring + Kotlin jars) that is six full inflate/deflate round-trips per class — the
 * deflate codec and the redundant jar I/O dominate cold-build cost.
 *
 * This object fuses the chain into ONE walk: a class is inflated once, run through all six per-class
 * transforms in order in-memory, and deflated once ([ClasspathMirror.mirrorAll]). The transforms are the
 * SAME implementations the per-pass entry points expose, called on the SAME bytes in the SAME order, so
 * the fused output is byte-for-byte what the six sequential mirrors produced — see [fuseClass].
 *
 * ## Generated-class flow (the soundness-critical wrinkle)
 *
 * Most passes rewrite a class in place (Coroutine/String/Switch/ResidualIndy/Math emit only the rewritten
 * owner; Switch/String additionally emit helper *methods* into that same owner, which therefore flow
 * forward inside the owner's bytes). [LambdaBytecode], however, emits NEW generated classes (one per
 * lambda site). In the old per-pass design those generated classes were written to the mirror by the
 * lambda pass, and the LATER passes (switch, residual-indy, math) then picked them up as ordinary new
 * classpath entries and transformed them — while the EARLIER passes (coroutine, string) never saw them
 * (they didn't exist yet when those passes ran).
 *
 * [fuseClass] reproduces exactly that: a class generated by pass `i` is fed only through the DOWNSTREAM
 * passes `i+1 .. n-1`, never the upstream ones. Get this wrong and the fused output diverges from the
 * per-pass output (a generated class would be over- or under-transformed). The
 * [DesugarFusionEquivalenceTest] golden-bytes test pins that it does not.
 */
internal object DesugarPasses {

    /**
     * The six per-class transforms, in the canonical order
     * `Coroutine -> String -> Lambda -> Switch -> ResidualIndy -> Math` — identical to
     * [JbmcBackend.applyDesugarPasses] and [GradleClasspathMirror.mirror]. Each entry rewrites one
     * class's bytes and may emit extra generated classes (only [LambdaBytecode] does today).
     */
    @JvmField
    val TRANSFORMS: List<ClasspathMirror.ClassTransform> = listOf(
            ClasspathMirror.ClassTransform { b -> ClasspathMirror.Transformed(CoroutineBytecode.stripClassForFusion(b)) },
            ClasspathMirror.ClassTransform { b -> ClasspathMirror.Transformed(StringBytecode.rewriteClass(b)) },
            ClasspathMirror.ClassTransform { b -> LambdaBytecode.transformForFusion(b) },
            ClasspathMirror.ClassTransform { b -> ClasspathMirror.Transformed(SwitchBytecode.rewriteClass(b)) },
            ClasspathMirror.ClassTransform { b -> ClasspathMirror.Transformed(ResidualIndyBytecode.rewriteClass(b)) },
            ClasspathMirror.ClassTransform { b -> ClasspathMirror.Transformed(MathBytecode.rewriteClass(b)) })

    /**
     * A short, stable identity for the fused pass list — folded into the mirror cache key so a fused
     * mirror never aliases a single-pass mirror (different cache namespace) and a change to the pass set
     * re-mirrors. The pass CODE identity is already carried by [Bmc4jVersion.IDENTITY]
     * (see [ClasspathMirror.effectiveExtraKey]); this only distinguishes the fused namespace and arity.
     */
    const val CACHE_NAME = "fused-desugar"

    /**
     * The fused per-class transform: run [bytes] through every pass in [TRANSFORMS] in order, threading a
     * class generated by pass `i` through the DOWNSTREAM passes `i+1 ..` only — exactly as the old
     * per-pass walk did (where later passes saw a generated class as a fresh classpath entry and earlier
     * ones never saw it). Returns the fully-desugared main class plus the transitive closure of generated
     * classes, each itself fully desugared by its downstream passes.
     */
    fun fuseClass(bytes: ByteArray): ClasspathMirror.Transformed {
        // Run the MAIN class through every pass; collect generated classes tagged with the pass that
        // produced them (so each can later resume at the next pass).
        val out = LinkedHashMap<String, ByteArray>()
        // Pending = classes still owing downstream passes: (internalName, bytes, nextPassIndex).
        val pending = ArrayDeque<Pending>()

        var cur = bytes
        for (i in TRANSFORMS.indices) {
            val t = TRANSFORMS[i].apply(cur)
            cur = t.main
            // A class generated AT pass i must be run through passes i+1.. (the downstream set), exactly
            // as the per-pass walk fed a lambda pass's new entries to switch/residual-indy/math only.
            for ((genName, genBytes) in t.extra) {
                pending.addLast(Pending(genName, genBytes, i + 1))
            }
        }
        // The main class is the result of the whole chain; it has no internal name from this transform's
        // point of view (the caller knows the entry path), so it is returned as `main`.
        val mainResult = cur

        // Drain generated classes, each resuming at its born-pass's successor. A class generated by a
        // downstream pass can itself generate more (e.g. a lambda-generated class hitting a later lambda
        // pass — not possible today since Lambda is the only generator and it is a single pass, but the
        // loop is general so a future second generator stays sound).
        while (pending.isNotEmpty()) {
            val p = pending.removeFirst()
            var gb = p.bytes
            for (i in p.nextPass until TRANSFORMS.size) {
                val t = TRANSFORMS[i].apply(gb)
                gb = t.main
                for ((genName, genBytes) in t.extra) {
                    pending.addLast(Pending(genName, genBytes, i + 1))
                }
            }
            // Deterministic last-writer-wins de-dup, matching ClasspathMirror.rewriteJarTo's LinkedHashMap
            // (a given generated name is deterministic per source, so a collision is identical content).
            out[p.internalName] = gb
        }
        return ClasspathMirror.Transformed(mainResult, out)
    }

    private class Pending(
            @JvmField val internalName: String,
            @JvmField val bytes: ByteArray,
            @JvmField val nextPass: Int)
}
