package org.bmc4j.engine;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.google.gson.JsonParser;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Unit tests for the stub-detection positive floor. The floor exists because the stub harvest keys
 * on a literal engine string — a format drift in a {@code -Dbmc.jbmc} engine silently empties it.
 * These tests pin the pieces that make the canary a valid floor (its stub survives the filter, its
 * bytecode really calls the missing method, the harvest extracts it from the pinned message shape)
 * and the failure path's behavior (loud engine-infrastructure UNKNOWN, memoized, marker-trusting).
 * The success path runs live in every example module: the first all-modeled green triggers the
 * canary against the bundled engine.
 */
class StubHarvestFloorTest {

    @Test
    void canary_stub_survives_the_signal_filter() {
        // The floor exercises the FULL harvest pipeline, filter included — if a future StubFilter
        // rule swallowed the canary's package, every floor probe would fail (loud, but wrong).
        assertTrue(StubFilter.isSignal(StubHarvestFloor.CANARY_STUB_FQN),
                "the canary stub must be classified as signal or the floor cannot work");
    }

    @Test
    void canary_harvests_from_the_pinned_message_shape() {
        // Ties the canary constant to the parser's opaque-symbol extraction: the exact message the
        // engine emits for the canary's missing method must harvest to CANARY_STUB_FQN.
        String json = """
            [
              {"messageType":"STATUS-MESSAGE",
               "messageText":"Generating codet:  new opaque symbol: method 'java::bmc.canary.Missing.gone:()V'"}
            ]""";
        List<String> stubs = JbmcOutputParser.harvestStubs(
                JsonParser.parseString(json).getAsJsonArray());
        assertEquals(List.of(StubHarvestFloor.CANARY_STUB_FQN), stubs,
                "the canary's opaque-symbol message must harvest to the canary FQN");
    }

    @Test
    void probe_class_really_calls_the_missing_method() {
        // Guards the generated bytecode against bitrot: the probe must INVOKESTATIC the missing
        // class that CANARY_STUB_FQN names, or the engine has nothing to stub.
        AtomicBoolean sawCall = new AtomicBoolean();
        new ClassReader(StubHarvestFloor.probeClass()).accept(new ClassVisitor(Opcodes.ASM9) {
            @Override
            public MethodVisitor visitMethod(int a, String name, String d, String s, String[] ex) {
                return new MethodVisitor(Opcodes.ASM9) {
                    @Override
                    public void visitMethodInsn(int op, String owner, String m, String desc, boolean i) {
                        if (op == Opcodes.INVOKESTATIC && owner.equals("bmc/canary/Missing")
                                && m.equals("gone")) {
                            sawCall.set(true);
                        }
                    }
                };
            }
        }, 0);
        assertTrue(sawCall.get(), "the probe must call bmc.canary.Missing.gone");
        assertTrue(StubHarvestFloor.CANARY_STUB_FQN.equals("bmc.canary.Missing.gone"),
                "constant and bytecode must name the same missing method");
    }

    @Test
    void unverifiable_engine_fails_loud_and_memoizes(@TempDir Path home) throws Exception {
        runWithHome(home, () -> {
            String identity = "test-engine-bogus-" + System.nanoTime();
            int before = StubHarvestFloor.CANARY_RUNS.get();

            // A jbmc path that cannot run: the canary cannot vouch -> loud infrastructure UNKNOWN.
            BmcUndecidedError e = assertThrows(BmcUndecidedError.class,
                    () -> StubHarvestFloor.ensure(home.resolve("no-such-jbmc.exe").toString(), identity));
            assertTrue(e.isEngineInfrastructure(),
                    "a failed floor is an engine-infrastructure UNKNOWN (never satisfies expect=UNKNOWN)");
            assertTrue(e.getMessage().contains("stub detection"), e.getMessage());
            assertEquals(before + 1, StubHarvestFloor.CANARY_RUNS.get(), "the canary ran once");

            // Same engine identity again: memoized verdict, no second canary run, still loud.
            assertThrows(BmcUndecidedError.class,
                    () -> StubHarvestFloor.ensure(home.resolve("no-such-jbmc.exe").toString(), identity));
            assertEquals(before + 1, StubHarvestFloor.CANARY_RUNS.get(),
                    "the floor verdict is memoized per engine identity");
        });
    }

    @Test
    void disk_marker_from_a_prior_jvm_is_trusted(@TempDir Path home) throws Exception {
        runWithHome(home, () -> {
            String identity = "test-engine-marked-" + System.nanoTime();
            String key = identity + '|' + Bmc4jVersion.IDENTITY;
            Path marker = StubHarvestFloor.markerPath(key);
            Files.createDirectories(marker.getParent());
            Files.writeString(marker, "ok\n");

            int before = StubHarvestFloor.CANARY_RUNS.get();
            // Bogus engine path, but the marker says a prior JVM proved this (engine, runtime)
            // pair — the floor passes without running the canary.
            StubHarvestFloor.ensure(home.resolve("no-such-jbmc.exe").toString(), identity);
            assertEquals(before, StubHarvestFloor.CANARY_RUNS.get(),
                    "a disk marker for this engine+runtime skips the canary entirely");
        });
    }

    /** Run {@code body} with {@code user.home} redirected so floor markers stay in the temp dir. */
    private static void runWithHome(Path home, ThrowingRunnable body) throws Exception {
        String prev = System.getProperty("user.home");
        System.setProperty("user.home", home.toAbsolutePath().toString());
        try {
            body.run();
        } finally {
            System.setProperty("user.home", prev);
        }
    }

    @FunctionalInterface
    private interface ThrowingRunnable {
        void run() throws Exception;
    }
}
