package org.bmc4j.constraints

/**
 * Renders a reflection-free `<Type>Constraints` helper from a model class's
 * extracted constraints. The generated `assumeValid` calls
 * `org.bmc4j.Bmc.assume(...)` for each constraint, so JBMC sees the
 * preconditions as plain bytecode.
 */
object ConstraintCodeGenerator {

    /** A model field plus the accessor used to read it and its constraints. */
    class Field(@JvmField val accessor: String, @JvmField val constraints: List<Constraint>)

    /**
     * @param packageName         package of the generated class (may be empty or null)
     * @param generatedSimpleName e.g. `UserConstraints`
     * @param targetTypeFqn       the model type, e.g. `com.acme.User`
     * @param paramName           the parameter name used in the generated method (e.g. `obj`)
     * @param fields              fields whose accessors are already expressed in terms of [paramName]
     */
    @JvmStatic
    fun generate(packageName: String?, generatedSimpleName: String,
                 targetTypeFqn: String, paramName: String, fields: List<Field>): String = buildString {
        if (!packageName.isNullOrEmpty()) {
            append("package ").append(packageName).append(";\n\n")
        }
        append("// Generated by bmc-constraints from validation annotations. Do not edit.\n")
        append("public final class ").append(generatedSimpleName).append(" {\n\n")
        append("    private ").append(generatedSimpleName).append("() {}\n\n")

        append("    /** Assume ").append(paramName)
                .append(" satisfies its validation constraints. */\n")
        append("    public static void assumeValid(").append(targetTypeFqn).append(' ')
                .append(paramName).append(") {\n")
        // A validated object exists; assume non-null before reading its fields.
        append("        org.bmc4j.Bmc.assume(").append(paramName).append(" != null);\n")
        for (f in fields) {
            for (c in f.constraints) {
                append("        org.bmc4j.Bmc.assume(")
                        .append(c.toExpression(f.accessor)).append(");\n")
            }
        }
        append("    }\n")
        append("}\n")
    }
}
